[build]
  publish = "."
  ignore = "emtech_backend/*"

[[redirects]]
  from = "/api/*"
  to = "https://kick-n-klean-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 