[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[[redirects]]
  from = "/api/*"
  to = "https://erawr.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/Main.html"
  status = 200 