[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r emtech_backend/requirements.txt"]

[phases.build]
cmds = [
  "cd emtech_backend",
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[start]
cmd = "cd emtech_backend && gunicorn emtech_backend.wsgi:application --bind 0.0.0.0:$PORT" 